name: Danger?

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  danger:
    name: Danger?
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Danger?
        run: ./build.sh ${{ github.event.pull_request.id }}
