name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Prettier
        run: npx prettier --check .

      - name: GHA Variables
        run: |
          echo pr.base.sha ${{ github.event.pull_request.base.sha }}
          echo pr.head.sha ${{ github.event.pull_request.head.sha }}

      - name: Runner Variables
        run: env
